- hosts: all
  gather_facts: true
  tasks: 
  - name: "install nginx"
    package:
      name: nginx
      state: absent
    when: ansible_os_family=="Debian" 
   
  - name: "install nginx"
    package:
      name: nginx
      state: absent
    when: ansible_os_family=="RedHat"